# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\pyqt\test07\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 60, 571, 271))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.page_1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 121, 101))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bt_file1 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_file1.setObjectName(_fromUtf8("bt_file1"))
        self.verticalLayout_2.addWidget(self.bt_file1)
        self.bt_file2 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bt_file2.setObjectName(_fromUtf8("bt_file2"))
        self.verticalLayout_2.addWidget(self.bt_file2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.page_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(200, 30, 341, 101))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_1 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.verticalLayout_3.addWidget(self.label_1)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayoutWidget = QtGui.QWidget(self.page_1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 121, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_main_key_F = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_main_key_F.setObjectName(_fromUtf8("comboBox_main_key_F"))
        self.horizontalLayout.addWidget(self.comboBox_main_key_F)
        self.label_key_F = QtGui.QLabel(self.page_1)
        self.label_key_F.setGeometry(QtCore.QRect(10, 240, 241, 20))
        self.label_key_F.setObjectName(_fromUtf8("label_key_F"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.page_1)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(200, 150, 91, 80))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.comboBox_sheet_main_F = QtGui.QComboBox(self.verticalLayoutWidget_7)
        self.comboBox_sheet_main_F.setObjectName(_fromUtf8("comboBox_sheet_main_F"))
        self.verticalLayout_7.addWidget(self.comboBox_sheet_main_F)
        self.comboBox_sheet_fu_F = QtGui.QComboBox(self.verticalLayoutWidget_7)
        self.comboBox_sheet_fu_F.setObjectName(_fromUtf8("comboBox_sheet_fu_F"))
        self.verticalLayout_7.addWidget(self.comboBox_sheet_fu_F)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.page_1)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(340, 150, 160, 80))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_sheet_main_F = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_sheet_main_F.setObjectName(_fromUtf8("label_sheet_main_F"))
        self.verticalLayout_8.addWidget(self.label_sheet_main_F)
        self.label_sheet_fu_F = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_sheet_fu_F.setObjectName(_fromUtf8("label_sheet_fu_F"))
        self.verticalLayout_8.addWidget(self.label_sheet_fu_F)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.page_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 50, 111, 161))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.bt_directory = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.bt_directory.setObjectName(_fromUtf8("bt_directory"))
        self.verticalLayout_5.addWidget(self.bt_directory)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.page_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(189, 70, 351, 121))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_directory = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_directory.setObjectName(_fromUtf8("label_directory"))
        self.verticalLayout_6.addWidget(self.label_directory)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.page_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(360, 210, 160, 61))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox_row = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_row.setObjectName(_fromUtf8("checkBox_row"))
        self.horizontalLayout_2.addWidget(self.checkBox_row)
        self.checkBox_col = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_col.setObjectName(_fromUtf8("checkBox_col"))
        self.horizontalLayout_2.addWidget(self.checkBox_col)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 90, 131, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.bt_func_R = QtGui.QPushButton(self.verticalLayoutWidget)
        self.bt_func_R.setObjectName(_fromUtf8("bt_func_R"))
        self.verticalLayout.addWidget(self.bt_func_R)
        self.bt_func_L = QtGui.QPushButton(self.verticalLayoutWidget)
        self.bt_func_L.setObjectName(_fromUtf8("bt_func_L"))
        self.verticalLayout.addWidget(self.bt_func_L)
        self.bt_func_D = QtGui.QPushButton(self.verticalLayoutWidget)
        self.bt_func_D.setObjectName(_fromUtf8("bt_func_D"))
        self.verticalLayout.addWidget(self.bt_func_D)
        self.textBrowser = QtGui.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(190, 340, 351, 91))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_mode = QtGui.QLabel(self.centralWidget)
        self.label_mode.setGeometry(QtCore.QRect(340, 40, 181, 16))
        self.label_mode.setObjectName(_fromUtf8("label_mode"))
        self.checkBox = QtGui.QCheckBox(self.centralWidget)
        self.checkBox.setGeometry(QtCore.QRect(610, 410, 119, 16))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.bt_start = QtGui.QPushButton(self.centralWidget)
        self.bt_start.setGeometry(QtCore.QRect(610, 490, 119, 23))
        self.bt_start.setObjectName(_fromUtf8("bt_start"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_func = QtGui.QMenu(self.menuBar)
        self.menu_func.setObjectName(_fromUtf8("menu_func"))
        self.menu_help = QtGui.QMenu(self.menuBar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_set = QtGui.QMenu(self.menuBar)
        self.menu_set.setObjectName(_fromUtf8("menu_set"))
        MainWindow.setMenuBar(self.menuBar)
        self.action_R = QtGui.QAction(MainWindow)
        self.action_R.setObjectName(_fromUtf8("action_R"))
        self.action_L = QtGui.QAction(MainWindow)
        self.action_L.setObjectName(_fromUtf8("action_L"))
        self.action_F = QtGui.QAction(MainWindow)
        self.action_F.setObjectName(_fromUtf8("action_F"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_helpdoc = QtGui.QAction(MainWindow)
        self.action_helpdoc.setObjectName(_fromUtf8("action_helpdoc"))
        self.action_set = QtGui.QAction(MainWindow)
        self.action_set.setObjectName(_fromUtf8("action_set"))
        self.menu_func.addAction(self.action_R)
        self.menu_func.addAction(self.action_L)
        self.menu_func.addAction(self.action_F)
        self.menu_help.addAction(self.action_helpdoc)
        self.menu_help.addAction(self.action_about)
        self.menu_set.addAction(self.action_set)
        self.menuBar.addAction(self.menu_func.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())
        self.menuBar.addAction(self.menu_set.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel Operator", None))
        self.bt_file1.setText(_translate("MainWindow", "选择主表", None))
        self.bt_file2.setText(_translate("MainWindow", "选择副表", None))
        self.label_1.setText(_translate("MainWindow", "您选择的文件：未选择", None))
        self.label_2.setText(_translate("MainWindow", "您选择的文件：未选择", None))
        self.label_key_F.setText(_translate("MainWindow", "主键第1行|列(默认第1个)", None))
        self.label_sheet_main_F.setText(_translate("MainWindow", "主表第1张(默认第1张)", None))
        self.label_sheet_fu_F.setText(_translate("MainWindow", "副表第1张(默认第1张)", None))
        self.bt_directory.setText(_translate("MainWindow", "选择文件夹", None))
        self.label_directory.setText(_translate("MainWindow", "您选择的文件夹：未选择", None))
        self.checkBox_row.setText(_translate("MainWindow", "行模式", None))
        self.checkBox_col.setText(_translate("MainWindow", "列模式", None))
        self.bt_func_R.setText(_translate("MainWindow", "行模式", None))
        self.bt_func_L.setText(_translate("MainWindow", "列模式", None))
        self.bt_func_D.setText(_translate("MainWindow", "文件模式", None))
        self.label_mode.setText(_translate("MainWindow", "模式：未选择", None))
        self.checkBox.setText(_translate("MainWindow", "默认相加(不询问)", None))
        self.bt_start.setText(_translate("MainWindow", "开始", None))
        self.menu_func.setTitle(_translate("MainWindow", "功能", None))
        self.menu_help.setTitle(_translate("MainWindow", "帮助", None))
        self.menu_set.setTitle(_translate("MainWindow", "配置文件", None))
        self.action_R.setText(_translate("MainWindow", "行模式 (R)", None))
        self.action_L.setText(_translate("MainWindow", "列模式 (L)", None))
        self.action_F.setText(_translate("MainWindow", "文件模式 (F)", None))
        self.action_about.setText(_translate("MainWindow", "关于", None))
        self.action_helpdoc.setText(_translate("MainWindow", "帮助文档", None))
        self.action_set.setText(_translate("MainWindow", "配置文件", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

